### ISSUE TITLE
Plugin not generated

### ISSUE THREAD

**Issue by Shepardgames** [jomarcenter-mjm/RMMVVSCodePluginGenerator#2]
Every time I try to generate a new plugin or the blank one it is saying "cannot generate js file".
Is there any dependencies that i need to download to get this working?

**Comment by jomarcenter-mjm** [comment]
Oh dear unless if node.js isn't installed on your vscode software, this is a bug. Will checked what happened.

**Comment by Shepardgames** [comment]
Thanks for the reply. I do have Node.js installed but not typescript can this be a problem?

**Comment by jomarcenter-mjm** [comment]
Visual studio uses JavaScript and typescript for plugin, so it should been working regardless.
